services:
  pgdatabase:
    image: postgres:13
    user: 1000:1000
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=globantds
    volumes:
      - "./globantDB_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

  hr-app:
    image: hr-app:0.5
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://root:root@pgdatabase:5432/globantds
    ports:
      - 8000:8000  
